export const moviesData = [
  {
    _id: '001',
    country: 'Россия',
    director: 'Неисзвестный 1',
    duration: 10,
    year: '2021',
    description: 'Описание',
    image: 'https://img.championat.com/i/j/h/16330040731357642319.jpg',
    nameRU: 'Лолита',
    nameEN: 'Lolita',
    trailerLink: 'https://www.youtube.com/watch?v=1jHz-NJOOiU',
  },
  {
    _id: '002',
    country: 'Россия',
    director: 'Неисзвестный 2',
    duration: 70,
    year: '2020',
    description: 'Описание',
    image: 'https://upload.wikimedia.org/wikipedia/ru/d/df/Greenland_%28film%29.jpg',
    nameRU: 'Длинааааааааааааааааааааааааааа',
    nameEN: 'Long',
    trailerLink: 'https://www.youtube.com/watch?v=1jHz-NJOOiU',
  },
  {
    _id: '003',
    country: 'Россия',
    director: 'Неисзвестный 3',
    duration: 160,
    year: '2020',
    description: 'Описание',
    image: 'https://www.soyuz.ru/public/uploads/files/2/7485686/20220822135056d084215047.jpg',
    nameRU: 'Название',
    nameEN: 'Name',
    trailerLink: 'https://www.youtube.com/watch?v=1jHz-NJOOiU',
  },
  {
    _id: '004',
    country: 'Россия',
    director: 'Неисзвестный 4',
    duration: 169,
    year: '2023',
    description: 'Описание',
    image: 'https://www.kovinov.com/biblioteka/filmy/filmy-o-pohodah-gorah-i-prikljuchenijah/Neverojatnaja-zhizn-m.jpg',
    nameRU: 'Бригада',
    nameEN: 'Name',
    trailerLink: 'https://www.youtube.com/watch?v=1jHz-NJOOiU',
  },
  {
    _id: '005',
    country: 'Россия',
    director: 'Неисзвестный 5',
    duration: 52,
    year: '2011',
    description: 'Описание',
    image: 'https://img.championat.com/i/j/h/16330040731357642319.jpg',
    nameRU: 'Операция Ы',
    nameEN: 'Name',
    trailerLink: 'https://www.youtube.com/watch?v=1jHz-NJOOiU',
  },
  {
    _id: '006',
    country: 'Россия',
    director: 'Неисзвестный 6',
    duration: 13,
    year: '2022',
    description: 'Описание',
    image: 'https://nashaplaneta.net/articles1/images/into-the-wild.jpg',
    nameRU: 'Название',
    nameEN: 'Name ',
    trailerLink: 'https://www.youtube.com/watch?v=1jHz-NJOOiU',
  },

];
