export const savedMoviesData = [
  {
    _id: '001',
    country: 'Россия',
    director: 'Неисзвестный 1',
    duration: 10,
    year: '2021',
    description: 'Описание',
    image: 'https://www.yaom.ru/wp-content/uploads/ganc-o-200x200.jpg',
    nameRU: 'Лолита',
    nameEN: 'Lolita',
    trailerLink: 'https://www.youtube.com/watch?v=1jHz-NJOOiU',
  },
  {
    _id: '002',
    country: 'Россия',
    director: 'Неисзвестный 2',
    duration: 70,
    year: '2020',
    description: 'Описание',
    image: 'https://upload.wikimedia.org/wikipedia/ru/d/df/Greenland_%28film%29.jpg',
    nameRU: 'Длинааааааааааааааааааааааааааа',
    nameEN: 'Long',
    trailerLink: 'https://www.youtube.com/watch?v=1jHz-NJOOiU',
  },
  {
    _id: '003',
    country: 'Россия',
    director: 'Неисзвестный 3',
    duration: 160,
    year: '2020',
    description: 'Описание',
    image: 'https://www.soyuz.ru/public/uploads/files/2/7485686/20220822135056d084215047.jpg',
    nameRU: 'Название',
    nameEN: 'Name',
    trailerLink: 'https://www.youtube.com/watch?v=1jHz-NJOOiU',
  },
];
